# Generated by Django 4.2.12 on 2024-05-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric_details', '0002_alter_purchaseorder_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histroicalperfomance',
            name='quality_rating_avg',
            field=models.FloatField(null=True),
        ),
    ]
